version: '2'
services:
  app:
    container_name: app
    build: .
    command: yarn start:dev
    volumes:
      - .:/LetsEat/API
    restart: always
    env_file:
        - .env
    ports:
      - "8080:8080"
    links:
      - postgres
    tty: true
    mem_limit: 300m

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    tty: true
    mem_limit: 50m

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./docker/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
    tty: true
    volumes_from:
      - app
    restart: always
