version: '2'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: yarn start:dev
    volumes:
      - .:/LetsEat/API
      - /LetsEat/API/node_modules/
    restart: always
    env_file:
        - .env
    ports:
      - "8080:8080"
    links:
      - postgres
      - redis
    tty: true
    mem_limit: 300m

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    tty: true
    mem_limit: 50m
    env_file:
      - .database.env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./docker/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
    tty: true
    volumes_from:
      - app
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/volumes/redis:/data
    env_file:
      - .env

  redis-cli:
    image: redis:latest
    container_name: redis-cli
    depends_on:
    - redis
    network_mode: host
    command: redis-cli HSET ${REDIS_API_KEY_HASHMAP} ${LETS_EAT_API_KEY} ""
    env_file:
      - .env