dry-run: null
hookfiles: ./src/shared/hooks/*.js
language: nodejs
sandbox: false
server: yarn start:test
server-wait: 30
init: false
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 2000
hooks-worker-after-connect-wait: 500
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 5000
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: apiary.apib
endpoint: 'http://127.0.0.1:8080'
